version: "3.9"

services:
  frontend:
    build:
      context: ./typescript/simple-mercari-web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:9000
    depends_on:
      - api

  api:
    build:
      context: ./go
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      - FRONT_URL=http://localhost:3000
    volumes:
      - ./go/db:/app/db
      - ./go/images:/app/images
